global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: otel-collector
    static_configs:
    - targets:
      - 'otelcol:8888'
  - job_name: customer
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'customer-svc:30001'
