linters-settings:
  dupl:
    threshold: 120
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 120
    statements: 50
  gocognit:
    min-complexity: 40
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    severity: "warning"
    confidence: 0.8
    rules:
      - name: dot-imports
      - name: error-return
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  skip-dirs:
    - deployments
