Name: customer
Environment: development

Web:
  Host: host.docker.internal
  Port: 30001

Rpc:
  Host: host.docker.internal
  Port: 30002

Mysql:
  Host: host.docker.internal
  Port: 3306
  User: "root"
  Password: "toor"
  Schema: "dev-local-customer-001"
  Charset: "utf8mb4"
  AutoMigration: false
  LogSQL: true
  SslMode: false
  MaxIdleConns: 1000
  MaxOpenConns: 100
  ConnMaxLifetime: 300

Consul:
  Host: host.docker.internal
  Port: 8500

Kafka:
  Brokers: [ "host.docker.internal:9092" ]
  GroupID: api_gateway_consumer
  InitTopics: true
