version: "3"

services:
  consul:
    container_name: consul-server
    image: hashicorp/consul:1.16
    restart: always
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    command: "agent"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    volumes:
      - ./consul/config/server.json:/consul/config/server.json:ro
    networks:
      - microservices-demo

networks:
  microservices-demo:
    driver: bridge

volumes:
  consuldata:
